#!/bin/sh
#    Small Operating System
#    Copyright (C) 2023 jmbert
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

set -x

if [ "$DISKSIZE" == "" ]; then
	printf "Specify disk size in \$DISKSIZE\n"
	exit -1
fi
if [ "$DISKCHUNKS" == "" ]; then
	printf "Specify disk chunk size in \$DISKSIZE\n"
	exit -1
fi

if [ "$1" == "" ]; then
	printf "Specify output disk as first argument\n"
	exit -1
fi

if [ "$2" == "" ]; then
	printf "Specify system directory as second argument\n"
	exit -1
fi

DISKFILE=$1

dd if=/dev/zero of=$DISKFILE bs=$DISKCHUNKS count=$DISKSIZE 

echo "
o

n




t
1

w" | fdisk $DISKFILE

LODEV=`sudo losetup -o $[2048*512] --sizelimit $[16*1024*1024] -f $DISKFILE --show`

sudo mkfs.fat -F 16 $LODEV

sudo mount --mkdir $LODEV /mnt/loopmnt
sudo mkdir /mnt/loopmnt/grub
sudo mkdir /mnt/loopmnt/EFI
sudo mkdir /mnt/loopmnt/EFI/grub

sudo grub-mkstandalone -O x86_64-efi -o BOOTX64.EFI "boot/grub/grub.cfg=grub_memdisk.cfg"

sudo cp BOOTX64.EFI /mnt/loopmnt/EFI/grub
sudo cp grub.cfg /mnt/loopmnt/grub/grub.cfg
sudo cp kernel.elf /mnt/loopmnt/kernel

sudo umount /mnt/loopmnt
sudo losetup -d $LODEV