#!/bin/bash

set -x

LODEV=`sudo losetup -o $[2048*512] --sizelimit $[16*1024*1024] -f kernel.dd --show`

sudo chown joe:joe $LODEV

qemu-system-x86_64 -d int,cpu_reset -m 1024 -net none -hda $LODEV -bios /usr/share/edk2-ovmf/x64/OVMF.fd 2>debug.log

sudo losetup -d $LODEV